on: [push, pull_request]
name: test and build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build
        run: |
          GOOS=linux   GOARCH=amd64 go build -o target/ci-test-linux-amd64
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: target/